Enhance Android build workflow for arm64-v8a
Updated Android build workflow to support arm64-v8a architecture with NDK r25-16k. Added manual trigger for release creation and improved artifact handling.

diff --git a/.github/workflows/android-build-scripts.yml b/.github/workflows/android-build-scripts.yml
--- a/.github/workflows/android-build-scripts.yml
+++ b/.github/workflows/android-build-scripts.yml
@@ -1,6 +1,7 @@
-name: android build scripts
+Name: android build scripts
 
 on:
+  workflow_dispatch: # Allows manual triggering, which will create a release
   push:
     branches:
       - development
@@ -26,11 +27,8 @@ on:
 
 jobs:
   build-main-on-linux:
-    name: android main on linux
+    name: android arm64-v8a on linux (ndk-r25-16k)
     runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        ndk-version: [ 'r22b-linux-x86_64', 'r23b-linux', 'r24-linux', 'r25b-linux' ]
     defaults:
       run:
         shell: bash
@@ -43,136 +41,55 @@ jobs:
           java-version: '17'
       - name: prerequisites
         run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1"
-      - name: set up android ndk
+      - name: set up android ndk r25 (16k support)
         run: |
-          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
+          curl -L -s "https://storage.googleapis.com/android-build/builds/aosp-ndk-release-r23-linux-linux/12186248/38c84da1ab0dd31ea40c857d2c9ee77450d9d71d76e60ac2ccd33d379babc534/android-ndk-12186248-linux-x86_64.zip?GoogleAccessId=gcs-sign%40android-builds-project.google.com.iam.gserviceaccount.com&Expires=1757434143&Signature=oK1FSeU9JpfoBkEqBZk%2FVmTH%2B1JJ09Dlv%2BsXblxpBTBq1kBA%2B42UPzbBpb%2BNy%2BIliEoWd2lO9Xbc92Lmzl1CiDyFwtzsxYE11nwUNNVWsjLvc0K0SO1%2F8j4p8b8eo5Zq5gc%2Bq7SamsrgelSUDSJfcYkDNR%2BE%2FyRpJgvtOqra%2FmEjw85pDrFMXFjZrSikYGjy%2Fl4E8TJRr%2BKh1BBkTEY5Oxvx3ia53LEzKE9bKKpFmFjZ9iXp%2BHh5ZSFPYZPrTMAeROSHlKARwvW35Bqgr%2FIyKHkSLKOk5%2FcbDud5iQwjuIB0l3MQTtkYr2TeDRh2BNzM82Z8MOwUfoncAI6nfj2%2Few%3D%3D" -o ndk.zip
           unzip -q -o ndk.zip -d .ndk
           echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
-      - name: run the build script
-        run: ./android.sh -d --enable-android-media-codec --enable-android-zlib --disable-arm-v7a
-      - name: print build logs
-        if: ${{ always() }}
-        run: cat build.log
-      - name: print ffbuild logs
-        if: ${{ failure() }}
-        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
-  build-lts-on-linux:
-    name: android lts on linux
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        ndk-version: [ 'r22b-linux-x86_64', 'r23b-linux' ]
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - uses: actions/checkout@v4
-      - name: set up adopt jdk 17
-        uses: actions/setup-java@v3
+      - name: run the build script (arm64-v8a only)
+        run: ./android.sh -d --full --enable-gpl --disable-arm-v7a --disable-arm-v7a-neon --disable-x86 --disable-x86-64
+      - name: prepare and upload main aar
+        run: |
+          AAR_PATH=$(find prebuilt -type f -name 'ffmpeg-kit.aar')
+          if [ -z "$AAR_PATH" ]; then
+            echo "Error: ffmpeg-kit.aar not found in prebuilt directory."
+            exit 1
+          fi
+          mv "$AAR_PATH" "ffmpeg-kit-arm64-v8a-ndk-r25-16k.aar"
+      - uses: actions/upload-artifact@v4
         with:
-          distribution: 'adopt'
-          java-version: '17'
-      - name: prerequisites
-        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1"
-      - name: set up android ndk
-        run: |
-          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
-          unzip -q -o ndk.zip -d .ndk
-          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
-      - name: run the build script
-        run: ./android.sh -d --lts --enable-android-media-codec --enable-android-zlib
+          name: ffmpeg-kit-arm64-v8a-aar
+          path: ffmpeg-kit-arm64-v8a-ndk-r25-16k.aar
+          if-no-files-found: error
       - name: print build logs
         if: ${{ always() }}
         run: cat build.log
       - name: print ffbuild logs
         if: ${{ failure() }}
         run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
-  build-main-on-macos:
-    name: android main on macos
-    runs-on: macos-12
-    strategy:
-      matrix:
-        ndk-version: [ 'r22b-darwin-x86_64', 'r23b-darwin', 'r24-darwin', 'r25b-darwin' ]
-    defaults:
-      run:
-        shell: bash
+
+  create-release:
+    name: create github release
+    needs: [build-main-on-linux]
+    runs-on: ubuntu-latest
+    if: github.event_name == 'workflow_dispatch'
+    permissions:
+      contents: write
     steps:
-      - uses: actions/checkout@v4
-      - name: set up adopt jdk 17
-        uses: actions/setup-java@v3
+      - name: set release tag
+        id: set_tag
+        run: echo "TAG_NAME=ffmpeg-kit-arm64-v8a-$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
+      - name: download all aar artifacts
+        uses: actions/download-artifact@v4
         with:
-          distribution: 'adopt'
-          java-version: '17'
-      - name: set up android ndk
-        run: |
-          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
-          unzip -q -o ndk.zip -d .ndk
-          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
-      - name: run the build script
-        run: ./android.sh -d --enable-android-media-codec --enable-android-zlib --disable-arm-v7a
-      - name: print build logs
-        if: ${{ always() }}
-        run: cat build.log
-      - name: print ffbuild logs
-        if: ${{ failure() }}
-        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
-  build-lts-on-macos:
-    name: android lts on macos
-    runs-on: macos-12
-    strategy:
-      matrix:
-        ndk-version: [ 'r22b-darwin-x86_64', 'r23b-darwin' ]
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - uses: actions/checkout@v4
-      - name: set up adopt jdk 17
-        uses: actions/setup-java@v3
+          path: aar-artifacts
+      - name: list downloaded files for debug
+        run: ls -R aar-artifacts
+      - name: create github release and upload assets
+        uses: softprops/action-gh-release@v2
         with:
-          distribution: 'adopt'
-          java-version: '17'
-      - name: set up android ndk
-        run: |
-          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
-          unzip -q -o ndk.zip -d .ndk
-          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
-      - name: run the build script
-        run: ./android.sh -d --lts --enable-android-media-codec --enable-android-zlib
-      - name: print build logs
-        if: ${{ always() }}
-        run: cat build.log
-      - name: print ffbuild logs
-        if: ${{ failure() }}
-        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
-  build-main-without-ffmpeg-kit-protocols-on-linux:
-    name: build without ffmpeg-kit protocols
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        ndk-version: [ 'r22b-linux-x86_64' ]
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - uses: actions/checkout@v4
-      - name: set up adopt jdk 17
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'adopt'
-          java-version: '17'
-      - name: prerequisites
-        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1"
-      - name: set up android ndk
-        run: |
-          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
-          unzip -q -o ndk.zip -d .ndk
-          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
-      - name: run the build script
-        run: ./android.sh --no-ffmpeg-kit-protocols --disable-x86 --disable-x86-64 --disable-arm-v7a --disable-arm-v7a-neon
-      - name: print build logs
-        if: ${{ always() }}
-        run: cat build.log
-      - name: print ffbuild logs
-        if: ${{ failure() }}
-        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
+          tag_name: ${{ env.TAG_NAME }}
+          name: "Android ARM64-v8a AAR (NDK r25-16k) - ${{ env.TAG_NAME }}"
+          body: "Automated release of Android AAR file built exclusively for arm64-v8a architecture using NDK r25 with 16kB page size support."
+          prerelease: true
+          files: aar-artifacts/*/*.aar
